---
apiVersion: v1
kind: ConfigMap
metadata:
  name: starboard
  labels:
    {{- include "starboard-operator.labels" . | nindent 4 }}
data:
  {{- with .Values.starboard.scanJobTolerations }}
  scanJob.tolerations: {{ . | toJson | quote }}
  {{- end }}
  {{- with .Values.starboard.scanJobAnnotations }}
  scanJob.annotations: {{ . | quote }}
  {{- end }}
  {{- with .Values.starboard.scanJobPodTemplateLabels }}
  scanJob.podTemplateLabels: {{ . | quote }}
  {{- end }}
  {{- if .Values.operator.vulnerabilityScannerEnabled }}
  vulnerabilityReports.scanner: {{ .Values.starboard.vulnerabilityReportsPlugin | quote }}
  {{- end }}
  {{- if .Values.operator.configAuditScannerEnabled }}
  configAuditReports.scanner: {{ .Values.starboard.configAuditReportsPlugin | quote }}
  {{- end }}
  {{- if .Values.operator.kubernetesBenchmarkEnabled }}
  kube-bench.imageRef: {{ required ".Values.kubeBench.imageRef is required" .Values.kubeBench.imageRef | quote }}
  {{- end }}
  {{- if .Values.operator.clusterComplianceEnabled }}
  compliance.failEntriesLimit: {{ required ".Values.compliance.failEntriesLimit is required" .Values.compliance.failEntriesLimit | quote }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: starboard
  labels:
    {{- include "starboard-operator.labels" . | nindent 4 }}
{{- if eq .Values.starboard.vulnerabilityReportsPlugin "Vul" }}
{{- with .Values.vul }}
{{- if .createConfig }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: starboard-vul-config
  labels:
    {{- include "starboard-operator.labels" $ | nindent 4 }}
data:
  vul.imageRef: {{ required ".Values.vul.imageRef is required" .imageRef | quote }}
  vul.mode: {{ .mode | quote }}
  {{- if .httpProxy }}
  vul.httpProxy: {{ .httpProxy | quote }}
  {{- end }}
  {{- if .httpsProxy }}
  vul.httpsProxy: {{ .httpsProxy | quote }}
  {{- end }}
  {{- if .serverInsecure }}
  vul.serverInsecure: {{ .serverInsecure | quote }}
  {{- end }}
  {{- if .noProxy }}
  vul.noProxy: {{ .noProxy | quote }}
  {{- end }}
  {{- range $key, $registry := .nonSslRegistries }}
  vul.nonSslRegistry.{{ $key }}: {{ $registry | quote }}
  {{- end }}
  {{- range $key, $registry := .registry.mirror }}
  vul.registry.mirror.{{ $key }}: {{ $registry | quote }}
  {{- end }}
  vul.severity: {{ .severity | quote }}
  vul.dbRepository: {{ .dbRepository | quote }}
  {{- if .ignoreUnfixed }}
  vul.ignoreUnfixed: {{ .ignoreUnfixed | quote }}
  {{- end }}
  {{- if .timeout }}
  vul.timeout: {{ .timeout | quote }}
  {{- end }}
  {{- with .ignoreFile }}
  vul.ignoreFile: |
{{- . | trim | nindent 4 }}
  {{- end }}
  {{- if eq .mode "ClientServer" }}
  vul.serverURL: {{ required ".Values.vul.serverURL is required" .serverURL | quote }}
  {{- end }}
  {{- with .resources }}
    {{- with .requests }}
      {{- if .cpu }}
  vul.resources.requests.cpu: {{ .cpu }}
      {{- end }}
      {{- if hasKey . "memory" }}
  vul.resources.requests.memory: {{ .memory }}
      {{- end }}
    {{- end }}
    {{- with .limits }}
      {{- if .cpu }}
  vul.resources.limits.cpu: {{ .cpu }}
      {{- end }}
      {{- if .memory }}
  vul.resources.limits.memory: {{ .memory }}
      {{- end }}
    {{- end }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: starboard-vul-config
  labels:
    {{- include "starboard-operator.labels" $ | nindent 4 }}
data:
  {{- if .githubToken }}
  vul.githubToken: {{ .githubToken | b64enc | quote }}
  {{- end }}
  {{- if eq .mode "ClientServer" }}
  {{- if .serverToken }}
  vul.serverToken: {{ .serverToken | b64enc | quote }}
  {{- end }}
  {{- if .serverCustomHeaders }}
  vul.serverCustomHeaders: {{ .serverCustomHeaders | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- if eq .Values.starboard.configAuditReportsPlugin "Conftest" }}
{{- with .Values.conftest }}
{{- if .createConfig }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: starboard-conftest-config
  labels:
    {{- include "starboard-operator.labels" $ | nindent 4 }}
data:
  conftest.imageRef: {{ required ".Values.conftest.imageRef is required" .imageRef | quote }}
  {{- with .resources }}
  conftest.resources.requests.cpu: {{ .requests.cpu | quote }}
  conftest.resources.requests.memory: {{ .requests.memory | quote }}
  conftest.resources.limits.cpu: {{ .limits.cpu | quote }}
  conftest.resources.limits.memory: {{ .limits.memory | quote }}
  {{- end }}
  {{- range $key, $val := .library }}
  conftest.library.{{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- range $key, $val := .policy }}
  conftest.policy.{{ $key }}.rego: {{ $val.rego | quote }}
  conftest.policy.{{ $key }}.kinds: {{ $val.kinds | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- if eq .Values.starboard.configAuditReportsPlugin "Polaris" }}
{{- with .Values.polaris }}
{{- if .createConfig }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: starboard-polaris-config
  labels:
    {{- include "starboard-operator.labels" $ | nindent 4 }}
data:
  polaris.imageRef: {{ required ".Values.polaris.imageRef is required" .imageRef | quote }}
  {{- with .resources }}
  polaris.resources.requests.cpu: {{ .requests.cpu | quote }}
  polaris.resources.requests.memory: {{ .requests.memory | quote }}
  polaris.resources.limits.cpu: {{ .limits.cpu | quote }}
  polaris.resources.limits.memory: {{ .limits.memory | quote }}
  {{- end }}
  polaris.config.yaml: |
  {{- toYaml .config | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
{{- if eq .Values.starboard.vulnerabilityReportsPlugin "Khulnasoft" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: starboard-khulnasoft-config
  labels:
     {{- include "starboard-operator.labels" . | nindent 4 }}
data:
  khulnasoft.imageRef: {{ required ".Values.khulnasoft.imageRef is required!" .Values.khulnasoft.imageRef | quote }}
  khulnasoft.serverURL: {{ required ".Values.khulnasoft.serverURL is required!" .Values.khulnasoft.serverURL | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: starboard-khulnasoft-config
  labels:
    {{- include "starboard-operator.labels" . | nindent 4 }}
data:
  khulnasoft.username: {{ required ".Values.khulnasoft.username is required!" .Values.khulnasoft.username | b64enc | quote }}
  khulnasoft.password: {{ required ".Values.khulnasoft.password is required!" .Values.khulnasoft.password | b64enc | quote }}
{{- end}}
